// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RealTimeChessAlphaSevenFrontEnd.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ChessPiece
    {
        /// <summary>
        /// Initializes a new instance of the ChessPiece class.
        /// </summary>
        public ChessPiece() { }

        /// <summary>
        /// Initializes a new instance of the ChessPiece class.
        /// </summary>
        public ChessPiece(int? chessPieceId = default(int?), int? matchPlayerId = default(int?), int? chessPieceTypeId = default(int?), string location = default(string), string destination = default(string), double? positionX = default(double?), double? positionY = default(double?), double? velocity = default(double?), double? heading = default(double?))
        {
            ChessPieceId = chessPieceId;
            MatchPlayerId = matchPlayerId;
            ChessPieceTypeId = chessPieceTypeId;
            Location = location;
            Destination = destination;
            PositionX = positionX;
            PositionY = positionY;
            Velocity = velocity;
            Heading = heading;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chessPieceId")]
        public int? ChessPieceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "matchPlayerId")]
        public int? MatchPlayerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chessPieceTypeId")]
        public int? ChessPieceTypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public string Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "destination")]
        public string Destination { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "positionX")]
        public double? PositionX { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "positionY")]
        public double? PositionY { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "velocity")]
        public double? Velocity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "heading")]
        public double? Heading { get; set; }

    }
}
