// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RealTimeChessAlphaSevenFrontEnd.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ChessMatch
    {
        /// <summary>
        /// Initializes a new instance of the ChessMatch class.
        /// </summary>
        public ChessMatch() { }

        /// <summary>
        /// Initializes a new instance of the ChessMatch class.
        /// </summary>
        public ChessMatch(int? chessMatchId = default(int?), int? numPlayers = default(int?), DateTime? matchStartTime = default(DateTime?), DateTime? matchEndTime = default(DateTime?), bool? isActive = default(bool?), bool? isDeleted = default(bool?), DateTime? created = default(DateTime?), DateTime? updated = default(DateTime?), DateTime? deleted = default(DateTime?), IList<MatchPlayer> matchPlayers = default(IList<MatchPlayer>))
        {
            ChessMatchId = chessMatchId;
            NumPlayers = numPlayers;
            MatchStartTime = matchStartTime;
            MatchEndTime = matchEndTime;
            IsActive = isActive;
            IsDeleted = isDeleted;
            Created = created;
            Updated = updated;
            Deleted = deleted;
            MatchPlayers = matchPlayers;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chessMatchId")]
        public int? ChessMatchId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numPlayers")]
        public int? NumPlayers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "matchStartTime")]
        public DateTime? MatchStartTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "matchEndTime")]
        public DateTime? MatchEndTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isActive")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDeleted")]
        public bool? IsDeleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public DateTime? Created { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updated")]
        public DateTime? Updated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deleted")]
        public DateTime? Deleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "matchPlayers")]
        public IList<MatchPlayer> MatchPlayers { get; set; }

    }
}
