// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RealTimeChessAlphaSevenFrontEnd.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PlayerType
    {
        /// <summary>
        /// Initializes a new instance of the PlayerType class.
        /// </summary>
        public PlayerType() { }

        /// <summary>
        /// Initializes a new instance of the PlayerType class.
        /// </summary>
        public PlayerType(int? playerTypeId = default(int?), string playerTypeName = default(string), int? turnOrder = default(int?), IList<MatchPlayer> matchPlayers = default(IList<MatchPlayer>))
        {
            PlayerTypeId = playerTypeId;
            PlayerTypeName = playerTypeName;
            TurnOrder = turnOrder;
            MatchPlayers = matchPlayers;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "playerTypeId")]
        public int? PlayerTypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "playerTypeName")]
        public string PlayerTypeName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "turnOrder")]
        public int? TurnOrder { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "matchPlayers")]
        public IList<MatchPlayer> MatchPlayers { get; set; }

    }
}
