// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RealTimeChessAlphaSevenFrontEnd.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ChessPieceType
    {
        /// <summary>
        /// Initializes a new instance of the ChessPieceType class.
        /// </summary>
        public ChessPieceType() { }

        /// <summary>
        /// Initializes a new instance of the ChessPieceType class.
        /// </summary>
        public ChessPieceType(int? chessPieceTypeId = default(int?), string chessPieceTypeName = default(string), int? chessPieceScoreValue = default(int?), int? velocity = default(int?), string imagePath = default(string), object legalMoves = default(object))
        {
            ChessPieceTypeId = chessPieceTypeId;
            ChessPieceTypeName = chessPieceTypeName;
            ChessPieceScoreValue = chessPieceScoreValue;
            Velocity = velocity;
            ImagePath = imagePath;
            LegalMoves = legalMoves;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chessPieceTypeId")]
        public int? ChessPieceTypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chessPieceTypeName")]
        public string ChessPieceTypeName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chessPieceScoreValue")]
        public int? ChessPieceScoreValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "velocity")]
        public int? Velocity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "imagePath")]
        public string ImagePath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "legalMoves")]
        public object LegalMoves { get; set; }

    }
}
