// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RealTimeChessAlphaSevenFrontEnd.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Player
    {
        /// <summary>
        /// Initializes a new instance of the Player class.
        /// </summary>
        public Player() { }

        /// <summary>
        /// Initializes a new instance of the Player class.
        /// </summary>
        public Player(int? playerId = default(int?), int? authenticationId = default(int?), string firstName = default(string), string lastName = default(string), int? numWins = default(int?), int? numLosses = default(int?), bool? isActive = default(bool?), bool? isDeleted = default(bool?), DateTime? created = default(DateTime?), DateTime? updated = default(DateTime?), DateTime? deleted = default(DateTime?), IList<MatchPlayer> matchPlayers = default(IList<MatchPlayer>))
        {
            PlayerId = playerId;
            AuthenticationId = authenticationId;
            FirstName = firstName;
            LastName = lastName;
            NumWins = numWins;
            NumLosses = numLosses;
            IsActive = isActive;
            IsDeleted = isDeleted;
            Created = created;
            Updated = updated;
            Deleted = deleted;
            MatchPlayers = matchPlayers;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "playerId")]
        public int? PlayerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "authenticationId")]
        public int? AuthenticationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numWins")]
        public int? NumWins { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numLosses")]
        public int? NumLosses { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isActive")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDeleted")]
        public bool? IsDeleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public DateTime? Created { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updated")]
        public DateTime? Updated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deleted")]
        public DateTime? Deleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "matchPlayers")]
        public IList<MatchPlayer> MatchPlayers { get; set; }

    }
}
